### ISSUE TITLE
Testing for 1.0.30.1 build (omor)

### ISSUE THREAD

**Issue by olga-jane** [olga-jane/prizm#1234]
All testing should be performed on fresh installation on Testing Mashine (log as Tester, Prism123)

- [x] An unhandled NullReferenceException arrives at "Настройки->Инспекторы". #1072  - check all grids which were affected by changes. Check not only exact scenario, but some other scenarios working with these grids.

- [x] "Измерение длины" OverflowException & Format Exception #1091 -  try to enter all kinds of numbers and strings. System shouldn't crash anyway.

- [x] Serious problem with required operations at joint #1184 - make sure that names of fixed operations don't affect the functionality

- [x] Please write compilation guide #1191 - make sure compilation guide is present, contains proper text and is readable.

- [x] Exeption on notification about welder's expired certificate #1193 

- [x] Client required: fixed sorted order at pipeTestResult grid #1201 - make sure nothing can break the consistency of rows at Mill inspection operations

- [x] Can save welders with expired sertificate #1204

- [x] Can save inspection operations without inspectors #1206

- [x] Notification exception #1213 

- [x] Do not re-create dialogs each time #1225 (EXTERNAL FILES part for 1) Component, 2) Spool, 3) Joint, 4) Pipe, 5) Release Note) - check that 1) all data entered and saved correctly, for some number of operations for sizetype (10?). 2) document closed correctly. 3) repeat the same and look if there are any problems. Write results of your testing here (maybe as a table in comments?)

- [x] Saving components with attached files in one transaction #1231 - please emulate impossibility to save files (f.e. restrict saving to directory?) so test both success and failure (whole entity shouldn't be saved if writing files will fail). Components only.

- [x] You can disable all "Права" for every registered used #1001

**Comment by AleksMorozova** [comment]
wrong validation of User TabPage
