### ISSUE TITLE
Testing for 1.0.30.1 build (dsyd)

### ISSUE THREAD

**Issue by olga-jane** [olga-jane/prizm#1235]
All testing should be performed on fresh installation on Testing Mashine (log as Tester, Prism123)

- [x] Logging #1057 : install fresh version on test environment and make sure that 1) logs are available 2) only errors written in Log both from our application and from NHibernate

- [x] Saving records without the "Инспектор" field in the "Входной контроль" form. #1081 (TESTED from 02.02.2014)

- [x] insert version to starting splash screen #1161 - make sure version is present and is the same as in about box and install script

- [x] Version change 1.0.30.x #1164 - make sure that version is everywhere (see previous task) is 1.0.30.1

- [x] When pipe status changed to Stocked, no changes reflected to screen #1185 - please check full scenario, when pipe goes from produced to stocked then to shipped, every time the status should be reflected in UI.

- [x] include log4net in installation package (already added to extern) #1196 - make sure logging is working at testing PC and log4net.dll is present after installation

- [x] Can enter lowercase numbers #1207 - please check on ALL screens, ALL fields related to numbers

- [x] Do not re-create dialogs each time #1225 (MILL PIPE part) - check that 1) all data entered and saved correctly, for some number of operations for sizetype (10?). 2) document closed correctly. 3) repeat the same and look if there are any problems.

- [x] Audit - wrong search by number+user and number+dates. Should be number+dates vs user+dates. #1104 please check that audit works now number+dates and user+dates, and Audit functionality works correctly.

- [x] In "Роли" no rights are initially selected #1210

**Comment by DmitrySidorov** [comment]
according to "Do not re-create dialogs each time #1225"
bug: 
- do not refresh comboBox "Код контрольної операції"
