### ISSUE TITLE
Testing for 1.0.31.1 build (omor)

### ISSUE THREAD

**Issue by olga-jane** [olga-jane/prizm#1366]
- [x] Component is saved without external files #1358
- [x] Hide plate thickness field from mill pipe screen #1350
- [x] Add file button should be at the left, Close at the right at ExternalFile dialog #1335
- [x] Attachments window should contain Close button #1122
- [x] On Adding External File, check max file size #1299
- [x] Saving empty row at Settings #1278
- [x] Вкладка Труба, флаг (*) изменений не очищается #1251
- [x] устанавливается флаг (*) изменений в настройках #1250
- [x] When you open a "Стык" it is always marked as changed #1113
- [x] Import does not give feedback to user to know that import already finished #1208
- [x] Loading (Shipping) report at Mill #1165 
- [x] Pipe Length doesn't refresh after adding or updating Length control operation #887

**Comment by AleksMorozova** [comment]
устанавливается флаг (*) изменений в настройках #1250 - didn't fix
