### ISSUE TITLE
Testing for 1.0.31.1 build (kuld)

### ISSUE THREAD

**Issue by olga-jane** [olga-jane/prizm#1367]
* [x] Date conversion crash at SaveSettings when create new sizetype #1334 
* [x] Crash on release note #1328
* [x] Настройки-Инспекторы: столбец уровень должен быть атрибутом сертификата #1303
* [x] Program accepts wrong dates #1301
* [x] good solution for using run.pat both on client side and our side #1297
* [x] troubles with release note and export (client 6 Feb 2015) #1280
* [x] Release note problems (client 6 Feb 2015) #1265
* [x] Impossible to send release note with "empty" railcars #1186
* [x] Save language settings as user settings #1032
* [x] Duplicate value at Settings #996
