### ISSUE TITLE
Testing for 1.0.31.1 build (dsyd)

### ISSUE THREAD

**Issue by olga-jane** [olga-jane/prizm#1368]
- [x] MillInspectionForm: comboboxes duplicate data #1327
- [x] one more rename: PrizmDatabase -> PrismDatabase in connection string settings #1315
- [x] Shipping parameters at Mill Pipe #1307
- [x] Pipe Length mask - unnecessary zeros 0000 #1306
- [x] Localization is not working: progress panel, form names, dialog titles etc #1285
- [x] Do not re-create dialogs each time (for 31 version) #1276
- [x] Missing icons and headers at #1126
- [x] In "Новый стык" button "Сохранить" is never active #1098
- [x] Can create a pipe with number that corresponds mask partially #1090
- [x] Deactivation action does not let know the user that it already saved #831

**Comment by DmitrySidorov** [comment]
done
