### ISSUE TITLE
Testing for 1.0.32.1 build

### ISSUE THREAD

**Issue by olga-jane** [olga-jane/prizm#1563]
please start testing for 1.0.32.1 build
- [x]		Сохранение в Настройках версия 1.0.32.9992 с первого раза не работает  DUPLICATE #1540 opened 3 hours ago by Chifuyu  1.0.32.x
AleksMorozova	 0
- [x]		Incorrect error of invalid value in Settings->Componentry v. 1.0.32.9992 bug bug - validation Coding HIGH priority Settings #1536 opened 4 hours ago by gasty  1.0.32.x
AleksMorozova	 2
- [x]		please get rid of resource leak while creating icons  bug bug - crash/performance/leak Coding COMMON HIGH priority #1528 opened 19 hours ago by olga-jane  1.0.32.x
kapcia	 0
- [x]		crash on pipe (double click on first inspection operation) bug bug - crash/performance/leak Coding HIGH priority Mill pipe #1523 opened a day ago by demmy  1.0.32.x
kapcia	 1
- [x]		Empty typesize is possible  bug bug - functional bug - validation Coding MEDIUM priority Settings #1520 opened a day ago by gasty  1.0.32.x
AleksMorozova	 0
- [x]		I can save checked empty rows in "типы сварочных швов"  DUPLICATE #1513 opened a day ago by YuriyZagorulko  1.0.32.x
AleksMorozova	 1
- [x]		Empty User  DUPLICATE #1512 opened a day ago by KnightDanila  1.0.32.x
AleksMorozova	 0
- [x]		Argument out of range exception in Search Pipeline Elements [Master] [Exception] 1.0.32.9991 bug bug - crash/performance/leak Coding Construction Incoming inspection MEDIUM priority #1510 opened a day ago by VladBekleneshev  1.0.32.x
AleksMorozova	 1
- [x]		Find deactivated pipe [Mill] v 1.0.32.9991  bug bug - crash/performance/leak Coding HIGH priority Mill pipe #1509 opened a day ago by AlexeyMityaev  1.0.32.x
AleksMorozova	 1
- [x]		Ввод стандартного текста в строковых контрольных операциях на трубе client req Coding HIGH priority Mill pipe #1498 opened 2 days ago by olga-jane  1.0.32.x  2 of 3
 DmitrySidorov	 0
- [x]		Логи - файлы по датам  client req Coding COMMON HIGH priority #1497 opened 2 days ago by olga-jane  1.0.32.x
DmitrySidorov	 0
- [x]		За ночь период зависания составил 25-30 секунд и общее время процессора для процесса Prism bug bug - crash/performance/leak CLIENT Coding DB & sql & Hibernate HIGH priority Mill pipe #1496 opened 2 days ago by olga-jane  1.0.32.x
demmy	 0
- [x]		Strange Roles 0_o  DUPLICATE #1487 opened 2 days ago by KnightDanila  1.0.32.x
AleksMorozova	 2
- [x]		unexpected error - "Сертификаты" then press 'Esc' or 'Alt' bug bug - crash/performance/leak Coding DUPLICATE MEDIUM priority Settings #1484 opened 2 days ago by YuriyZagorulko  1.0.32.x
AleksMorozova	 1
- [x]		Инспекторы и сертификаты - выбрать Ещё не существующего инспектора  DUPLICATE #1482 opened 2 days ago by Kosenko-Yuriy  1.0.32.x
AleksMorozova	 1
- [x]		Import button not available  bug bug - functional bug - UI Coding DUPLICATE Export/Import MEDIUM priority #1478 opened 2 days ago by Chifuyu  1.0.32.x
kapcia	 2
- [x]		Настройка-трубы: все равно зажигает признак изменения данных  bug bug - UI CLIENT Coding HIGH priority #1474 opened 2 days ago by olga-jane  1.0.32.x
kapcia	 0
- [x]		Empty database fields error  New bug #1473 opened 2 days ago by Jeanosis  1.0.32.x
AleksMorozova	 1
- [x]		Аудит вылетал с ошибкой  bug bug - crash/performance/leak CLIENT Coding HIGH priority Reports #1471 opened 2 days ago by olga-jane  1.0.32.x
kapcia	 1
- [x]		Результаты поисков не имеют сортировок по умолчанию bug bug - UI CLIENT Coding COMMON MEDIUM priority #1470 opened 2 days ago by olga-jane  1.0.32.x
demmy	 0
- [x]		Не корректно отображается статус трубы – На складе/Отгружена bug bug - functional bug - UI CLIENT Coding HIGH priority Mill pipe Release note #1468 opened 2 days ago by olga-jane  1.0.32.x
DmitrySidorov	 4
- [x]		Не корректно сортируется таблица Результаты поиска вкладки Поиск разрешений на отгрузку bug bug - UI CLIENT Coding MEDIUM priority Release note #1467 opened 2 days ago by olga-jane  1.0.32.x
demmy	 0
- [x]		Окно ввода пароля не переведено  bug bug - UI CLIENT Coding Documentation/Translation Security #1466 opened 2 days ago by olga-jane  1.0.32.x
kapcia	 0
- [x]		Crash at UsedProduct report creation  bug bug - crash/performance/leak Coding HIGH priority Reports #1457 opened 3 days ago by DmitrySidorov  1.0.32.x
DmitrySidorov	 0
- [x]		Choose role in empty user tab cause unhandled exception  New bug #1454 opened 3 days ago by Paradaimu  1.0.32.x
AleksMorozova	 2
- [x]		Deactivated button on import  bug bug - functional bug - UI Coding Export/Import MEDIUM priority #1448 opened 3 days ago by prag007  1.0.32.x
kapcia	 0
- [x]		In English version lables of text fields in "Change password" window are displaced bug bug - UI Coding COMMON MEDIUM priority #1447 opened 3 days ago by AlexeyMityaev  1.0.32.x
DmitrySidorov	 0
- [x]		We cannot change admin password  bug bug - functional Coding COMMON MEDIUM priority #1446 opened 3 days ago by KnightDanila  1.0.32.x
kapcia	 1
- [x]		Problem with SELECT componentry [Master] [Exception] bug bug - crash/performance/leak Coding Construction DB & sql & Hibernate HIGH priority Incoming inspection #1441 opened 3 days ago by VladBekleneshev  1.0.32.x
kapcia	 0
- [x]		You can't open the program if users have the same logins bug bug - functional Coding COMMON MEDIUM priority Settings #1440 opened 3 days ago by YuriyZagorulko  1.0.32.x
AleksMorozova	 1
- [x]		You can't select anything else, if you'll click on field with new user bug bug - validation Coding MEDIUM priority Settings #1439 opened 3 days ago by YuriyZagorulko  1.0.32.x
AleksMorozova	 3
- [x]		Unhandled NullReferenceException in Settings->Pipe form bug bug - crash/performance/leak bug - validation Coding HIGH priority Settings #1438 opened 3 days ago by IgorVskpsn  1.0.32.x
demmy	 0
- [x]		Problem with exit from program without saving [Exception] bug bug - crash/performance/leak Coding COMMON DUPLICATE MEDIUM priority #1436 opened 3 days ago by VladBekleneshev  1.0.32.x
 2
- [x]		Error because of Inspector with empty name  bug bug - crash/performance/leak Coding MEDIUM priority Settings #1432 opened 3 days ago by Jeanosis  1.0.32.x
AleksMorozova	 0
- [x]		Save language settings as user settings - additional fixes  Coding COMMON MEDIUM priority #1431 opened 3 days ago by olga-jane  1.0.32.x
kapcia	 0
- [x]		что-то нахомутано во вводе даты сварочных операций bug bug - functional CLIENT Coding MEDIUM priority Mill pipe #1428 opened 3 days ago by olga-jane  1.0.32.x
AleksMorozova	 1
- [x]		Crash in Notifications after double clicking on empty grid bug bug - crash/performance/leak Coding HIGH priority Notifications #1424 opened 3 days ago by TanyaPilipenko  1.0.32.x
AleksMorozova	 1
- [x]		Problem with create report - could not load devexpress library bug bug - crash/performance/leak Coding HIGH priority Reports #1422 opened 3 days ago by TanyaPilipenko  1.0.32.x
kapcia	 1
- [x]		Translate problems in different places  bug bug - UI Coding Documentation/Translation MEDIUM priority #1421 opened 3 days ago by Chifuyu  1.0.32.x
kapcia	 0
- [x]		Help->About, Dont show all message  bug bug - UI Coding COMMON MEDIUM priority #1420 opened 4 days ago by Chifuyu  1.0.32.x
demmy	 0
- [x]		Save/New Joint after joint cutting  bug bug - functional Coding Construction HIGH priority #1418 opened 4 days ago by DmitrySidorov  1.0.32.x
DmitrySidorov	 0
- [x]		Connection the elements with multiple common diameters  bug bug - functional Coding Construction HIGH priority #1416 opened 4 days ago by DmitrySidorov  1.0.32.x
DmitrySidorov	 0
- [x]		Close button does not work with an empty input field bug bug - crash/performance/leak Coding DUPLICATE HIGH priority Settings #1409 opened 4 days ago by YuriyZagorulko  1.0.32.x
 1
- [x]		Истечение срока годности пароля  bug bug - functional Coding COMMON MEDIUM priority #1406 opened 4 days ago by Chifuyu  1.0.32.x
kapcia	 2
- [x]		Error in "Inspectors" panel  bug bug - crash/performance/leak Coding HIGH priority Settings #1405 opened 4 days ago by Jeanosis  1.0.32.x
AleksMorozova	 0
- [x]		strange behaviour on SaveChanges? window in Settings  bug bug - functional Coding COMMON MEDIUM priority #1404 opened 4 days ago by KnightDanila  1.0.32.x
kapcia	 0
- [x]		"Close" button("Settings" panel) desn't work while wrong certificate bug bug - validation Coding MEDIUM priority Settings #1403 opened 4 days ago by Jeanosis  1.0.32.x
AleksMorozova	 0
- [x]		Problem with translation from English: Mill-Pipe, expected result and yes/no deactivation bug bug - functional bug - UI Coding MEDIUM priority Mill pipe #1401 opened 4 days ago by TanyaPilipenko  1.0.32.x
demmy	 0
- [x]		CheckBox "Deactivate pipe"  bug bug - functional Coding MEDIUM priority Mill pipe #1400 opened 4 days ago by TanyaPilipenko  1.0.32.x
kapcia	 0
- [x]		Ошибка создания базы данных при установке, имя проекта Master bug bug - crash/performance/leak bug - functional Coding HIGH priority Installation #1398 opened 4 days ago by Kosenko-Yuriy  1.0.32.x
demmy	 0
- [x]		Ошибка при запуске при наличии двух одинаковых логинов bug bug - crash/performance/leak Coding COMMON MEDIUM priority #1395 opened 4 days ago by Chifuyu  1.0.32.x
AleksMorozova	 0
- [x]		Version change from 1.0.31.1 to 1.0.32.1  Coding HIGH priority Version #1391 opened 4 days ago by olga-jane  1.0.32.x
kapcia	 0
- [x]		Translation issue in reports  bug bug - UI Coding Documentation/Translation MEDIUM priority Reports #1387 opened 5 days ago by KhabarlakKonstantin  1.0.32.x
kapcia	 0
- [x]		Can edit ReleaseNote when it is shipped  bug bug - functional bug - UI Coding HIGH priority Release note #1385 opened 7 days ago by KhabarlakKonstantin  1.0.32.x
kapcia	 0
- [x]		Notifications form is not localized  bug bug - UI Coding Documentation/Translation MEDIUM priority Notifications #1382 opened 7 days ago by DmitrySidorov  1.0.32.x
DmitrySidorov	 0
- [x]		First setupForm  bug bug - crash/performance/leak bug - functional bug - UI Coding LOW priority Settings #1373 opened 7 days ago by AleksMorozova  1.0.32.x
AleksMorozova	 0
- [x]		Do not re-create dialogs each time (for next version) bug bug - crash/performance/leak Coding COMMON MEDIUM priority Refactoring #1361 opened 7 days ago by olga-jane  1.0.32.x  2 of 2
 DmitrySidorov	 0
- [x]		Crash at exit when Modified is on  bug bug - crash/performance/leak Coding COMMON MEDIUM priority #1352 opened 8 days ago by olga-jane  1.0.32.x
kapcia	 0
- [x]		One-way binding approach for read-only text edits (statuses)  Coding COMMON MEDIUM priority Refactoring #1338 opened 9 days ago by olga-jane  1.0.32.x
DmitrySidorov	 0
- [x]		External files one-transaction in all other places Attachments bug bug - functional Coding MEDIUM priority Refactoring to_share_students #1313 opened 11 days ago by olga-jane  1.0.32.x  4 of 4
 AleksMorozova	 1
- [x]		InvalidOperationException: Collection was modified bug bug - crash/performance/leak CLIENT Coding DUPLICATE MEDIUM priority Mill pipe #1281 opened 14 days ago by olga-jane  1.0.32.x
 1
- [x]		деактивируются кнопки Сохранить и Сохранить/Создать (plate number cause) bug bug - functional CLIENT Coding MEDIUM priority Mill pipe #1277 opened 14 days ago by olga-jane  1.0.32.x
DmitrySidorov	 1
- [x]		Construction report: make size type combo much wider  bug bug - UI Coding Construction LOW priority Reports #1209 opened 18 days ago by olga-jane  1.0.32.x
kapcia	 0
- [x]		Pipe/joint closed not at once after closing confirmation  bug bug - functional bug - UI Coding MEDIUM priority Mill pipe #1205 opened 18 days ago by olga-jane  1.0.32.x
DmitrySidorov	 0
- [x]		Error arrived during saving changes to the table on the "Входной контроль" form. bug bug - crash/performance/leak Coding HIGH priority Incoming inspection reported_by_students #1082 opened 24 days ago by IgorVskpsn  1.0.32.x
AleksMorozova	 2
- [x]		Exeption in "Настройки"->"Трубы" with saving data bug - crash/performance/leak Coding LOW priority MEDIUM priority reported_by_students #1004 opened 29 days ago by YuliaKulinich  1.0.32.x
 2
- [x]		Pipe inspection operations grid in settings: operation code must be unique. bug bug - validation Coding MEDIUM priority reported_by_students Settings #994 opened 29 days ago by StaceyN  1.0.32.x

**Comment by AleksMorozova** [comment]
1) Pipe inspection operations grid in settings: operation code must be unique. #994 - didn't work
